#!/bin/sh

DEB_HOST_MULTIARCH=`dpkg-architecture -qDEB_HOST_MULTIARCH`

for file in debian/*.in;
do
	target=`echo $file|sed -e 's/...$//'`
	sed -e s/DEB_HOST_MULTIARCH/$DEB_HOST_MULTIARCH/g $file > $target
done

